import ContainerPrinc from "@/src/components/LayoutFolder/Layout";
import Providers from "../Providers";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientesLayout({ children }) {
  return (
    <>
      <Providers>
        <ContainerPrinc>{children}</ContainerPrinc>
      </Providers>
    </>
  );
}
